export const student = [
  {
    id: 1,
    class: "one",
    name: "Seth Beck",
    photo: "https://randomuser.me/api/portraits/men/43.jpg",
    scores: "A+",
    percentage: 92,
  },
  {
    id: 2,
    class: "two",
    name: "Gregory Herrera",
    photo: "https://randomuser.me/api/portraits/men/39.jpg",
    scores: "A",
    percentage: 74,
  },
  {
    id: 3,
    class: "three",
    name: "Leo Byrd",
    photo: "https://randomuser.me/api/portraits/men/10.jpg",
    scores: "A+",
    percentage: 90,
  },
  {
    id: 4,
    class: "one",
    name: "Joan Brewer",
    photo: "https://randomuser.me/api/portraits/women/5.jpg",
    scores: "A-",
    percentage: 65,
  },
  {
    id: 5,
    class: "two",
    name: "Dolores Nelson",
    photo: "https://randomuser.me/api/portraits/women/35.jpg",
    scores: "A",
    percentage: 70,
  },
  {
    id: 6,
    class: "three",
    name: "Vickie Davis",
    photo: "https://randomuser.me/api/portraits/women/79.jpg",
    scores: "D",
    percentage: 40,
  },
  {
    id: 7,
    class: "one",
    name: "Francisco Hunt",
    photo: "https://randomuser.me/api/portraits/men/94.jpg",
    scores: "A-",
    percentage: 60,
  },
  {
    id: 8,
    class: "two",
    name: "Ralph Palmer",
    photo: "https://randomuser.me/api/portraits/men/71.jpg",
    scores: "A+",
    percentage: 80,
  },
  {
    id: 9,
    class: "three",
    name: "Sharlene Hughes",
    photo: "https://randomuser.me/api/portraits/women/44.jpg",
    scores: "A",
    percentage: 70,
  },
  {
    id: 10,
    class: "one",
    name: "Marc Chapman",
    photo: "https://randomuser.me/api/portraits/men/44.jpg",
    scores: "A+",
    percentage: 90,
  },
  {
    id: 11,
    class: "two",
    name: "Caleb Lowe",
    photo: "https://randomuser.me/api/portraits/men/73.jpg",
    scores: "A",
    percentage: 70,
  },
  {
    id: 12,
    class: "three",
    name: "Neil Wood",
    photo: "https://randomuser.me/api/portraits/men/72.jpg",
    scores: "A-",
    percentage: 65,
  },
  {
    id: 13,
    class: "one",
    name: "Neil Morgan",
    photo: "https://randomuser.me/api/portraits/men/61.jpg",
    scores: "A",
    percentage: 70,
  },
  {
    id: 14,
    class: "two",
    name: "Andre Hill",
    photo: "https://randomuser.me/api/portraits/men/78.jpg",
    scores: "A+",
    percentage: 89,
  },
  {
    id: 15,
    class: "three",
    name: "Rachel Bates",
    photo: "https://randomuser.me/api/portraits/women/38.jpg",
    scores: "A",
    percentage: 72,
  },
  {
    id: 16,
    class: "one",
    name: "Chris Howell",
    photo: "https://randomuser.me/api/portraits/men/35.jpg",
    scores: "B",
    percentage: 55,
  },
  {
    id: 17,
    class: "two",
    name: "Dwight Rodriquez",
    photo: "https://randomuser.me/api/portraits/men/99.jpg",
    scores: "F",
    percentage: 30,
  },
  {
    id: 18,
    class: "three",
    name: "Nathaniel Griffin",
    photo: "https://randomuser.me/api/portraits/men/8.jpg",
    scores: "A",
    percentage: 70,
  },
  {
    id: 19,
    class: "one",
    name: "Doris Nelson",
    photo: "https://randomuser.me/api/portraits/women/63.jpg",
    scores: "C",
    percentage: 55,
  },
  {
    id: 20,
    class: "two",
    name: "Sally Williamson",
    photo: "https://randomuser.me/api/portraits/women/36.jpg",
    scores: "A+",
    percentage: 85,
  },
  {
    id: 21,
    class: "three",
    name: "Duane Mason",
    photo: "https://randomuser.me/api/portraits/men/9.jpg",
    scores: "B",
    percentage: 60,
  },
  {
    id: 22,
    class: "one",
    name: "Roberto Wallace",
    photo: "https://randomuser.me/api/portraits/men/96.jpg",
    scores: "A+",
    percentage: 90,
  },
  {
    id: 23,
    class: "two",
    name: "Jessie Fields",
    photo: "https://randomuser.me/api/portraits/women/9.jpg",
    scores: "F",
    percentage: 20,
  },
  {
    id: 24,
    class: "three",
    name: "Arianna Simmmons",
    photo: "https://randomuser.me/api/portraits/women/61.jpg",
    scores: "A+",
    percentage: 96,
  },
  {
    id: 25,
    class: "one",
    name: "Amelia Barnett",
    photo: "https://randomuser.me/api/portraits/women/51.jpg",
    scores: "D",
    percentage: 50,
  },
  {
    id: 26,
    class: "two",
    name: "Marcus Johnston",
    photo: "https://randomuser.me/api/portraits/men/8.jpg",
    scores: "A+",
    percentage: 92,
  },
  {
    id: 27,
    class: "three",
    name: "Eleanor Silva",
    photo: "https://randomuser.me/api/portraits/women/74.jpg",
    scores: "A-",
    percentage: 69,
  },
  {
    id: 28,
    class: "one",
    name: "Suzanne Owens",
    photo: "https://randomuser.me/api/portraits/women/15.jpg",
    scores: "C",
    percentage: 50,
  },
  {
    id: 29,
    class: "two",
    name: "Alan Barnett",
    photo: "https://randomuser.me/api/portraits/men/7.jpg",
    scores: "C+",
    percentage: 70,
  },
  {
    id: 30,
    class: "three",
    name: "Louis Vasquez",
    photo: "https://randomuser.me/api/portraits/men/45.jpg",
    scores: "C",
    percentage: 50,
  },
];
